<?php

/*
* Implements hook_field_formatter_info()
*/
function field_ellipsis_field_formatter_info() {
  return array(
    'text_trimmed_ellipsis' => array(
      'label' => t('Trimmed with ellipsis'),
      'field types' => array('text', 'text_long', 'text_with_summary'),
      'settings' => array('trim_length' => 600),
    ),
  );
}

/*
* Implements hook_field_formatter_settings_form()
*/
function field_ellipsis_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  $element = array();

  if (strpos($display['type'], '_trimmed') !== FALSE) {
    $element['trim_length'] = array(
      '#title' => t('Trim length'),
      '#type' => 'textfield',
      '#size' => 10,
      '#default_value' => $settings['trim_length'],
      '#element_validate' => array('element_validate_integer_positive'),
      '#required' => TRUE,
    );
  }

  return $element;
}

/*
* Implements hook_field_formatter_settings_summary()
*/
function field_ellipsis_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  $summary = '';

  if (strpos($display['type'], '_trimmed') !== FALSE) {
    $summary = t('Trim length') . ': ' . $settings['trim_length'];
  }

  return $summary;
}

/*
* Implements hook_field_formatter_view()
*/
function field_ellipsis_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  switch ($display['type']) {
    case 'text_trimmed_ellipsis':
      foreach ($items as $delta => $item) {
        $output = _text_sanitize($instance, $langcode, $item, 'value');
        if ($display['type'] == 'text_trimmed_ellipsis' && strlen($output) > $display['settings']['trim_length']) {
          $output = text_summary($output, $instance['settings']['text_processing'] ? $item['format'] : NULL, $display['settings']['trim_length']);
          $output = strip_tags($output . '...');
          $output = '<p>' . $output . '</p>';
        }
        $element[$delta] = array('#markup' => $output);
      }
      break;
  }

  return $element;
}
